server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

spring:
  application:
    name: eureka-client2
  zipkin:
    base-url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream